name: filmfan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  internet_connection_checker: ^0.0.1+4
  get_storage: ^2.0.3
  get: 4.6.5
  flutter: 
    sdk: flutter
  either_dart: ^0.1.4

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

